---
- name: Setup R and RStudio Server on localhost
  hosts: localhost
  become: true
  connection: local
  roles: # Install with ansible-galaxy install -r requirements.yml
    - r # Installs R
    - rstudio-server # Installs RStudio Server and deploys

  vars:
    r_install_dev: true # Allow building R from source

    r_install:
      - build-essential
      - libcurl4-openssl-dev
      - libxml2-dev
      - libssl-dev
      - libfontconfig1-dev
      - libbz2-dev
      - liblzma-dev
      - libpcre2-dev
      - libpng-dev
      - libjpeg-dev
      - libtiff-dev
      - libicu-dev
      - libgmp-dev
      - libgsl-dev
      - libmagick++-dev
      - zlib1g-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - libfreetype6-dev
      - libhdf5-dev
      - libfftw3-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libxt-dev
      - xorg-dev
      - texinfo
      - texlive-base
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - pandoc

    rstudio_user: "{{ ansible_user | default('fabian') }}" # Replace with target RStudio user's name

    preferences:
      save_workspace: "never"
      load_workspace: false
      always_save_history: false
      restore_last_project: false
      jobs_tab_visibility: "shown"
      insert_matching: false
      insert_native_pipe_operator: true
      highlight_selected_line: true
      highlight_r_function_calls: true
      rainbow_parentheses: true
      tab_multiline_completion: true
      check_unexpected_assignment_in_function_call: true
      show_diagnostics_other: true
      syntax_color_console: true
      auto_expand_error_tracebacks: true
      console_double_click_select: true
      editor_theme: "Idle Fingers"
      help_font_size_points: 11
      font_size_points: 12
      visual_markdown_editing_show_doc_outline: false
      visual_markdown_editing_show_margin: true
      spelling_dictionary_language: "en_GB"
      panes:
        quadrants:
          - Source
          - Console
          - TabSet1
          - TabSet2
        tabSet1:
          - Environment
          - History
          - Build
          - VCS
          - Connections
          - Presentation
        tabSet2:
          - Files
          - Plots
          - Packages
          - Help
          - Viewer
          - Presentations
        hiddenTabSet:
          - Tutorial
        console_left_on_top: false
        console_right_on_top: true
        additional_source_columns: 0
      show_invisibles: true
      source_with_echo: true
      show_hidden_files: true
      rmd_viewer_type: "pane"
      global_theme: "alternate"

    keybindings:
      styler::style_active_file: "Ctrl+-"
      golem::run_dev: "Ctrl++"
      devtools::test_active_file: "Ctrl+T"

  tasks:
    - name: Ensure the RStudio preferences directory exists
      ansible.builtin.file:
        path: /home/{{ rstudio_user }}/.config/rstudio
        state: directory
        mode: "0755"
        owner: "{{ rstudio_user }}"
        group: "{{ rstudio_user }}"
      become: false

    - name: Check if rstudio-prefs.json already exists
      ansible.builtin.stat:
        path: /home/{{ rstudio_user }}/.config/rstudio/rstudio-prefs.json
      register: rstudio_prefs_stat
      become: false

    - name: Backup existing rstudio-prefs.json
      ansible.builtin.copy:
        src: /home/{{ rstudio_user }}/.config/rstudio/rstudio-prefs.json
        dest: /home/{{ rstudio_user }}/.config/rstudio/rstudio-prefs.json.backup.{{ ansible_date_time.epoch }}
        remote_src: true
        owner: "{{ rstudio_user }}"
        group: "{{ rstudio_user }}"
        mode: "0644"
      when: rstudio_prefs_stat.stat.exists
      become: false

    - name: Create or update rstudio-prefs.json
      ansible.builtin.copy:
        dest: /home/{{ rstudio_user }}/.config/rstudio/rstudio-prefs.json
        content: |
          {{ preferences | to_nice_json }}
        owner: "{{ rstudio_user }}"
        group: "{{ rstudio_user }}"
        mode: "0644"
      notify: restart rstudio-server
      become: false

    - name: Ensure the keybindings directory exists
      ansible.builtin.file:
        path: /home/{{ rstudio_user }}/.config/rstudio/keybindings
        state: directory
        mode: "0755"
        owner: "{{ rstudio_user }}"
        group: "{{ rstudio_user }}"
      become: false

    - name: Create or update addins.json
      ansible.builtin.copy:
        dest: /home/{{ rstudio_user }}/.config/rstudio/keybindings/addins.json
        content: |
          {{ keybindings | to_nice_json }}
        owner: "{{ rstudio_user }}"
        group: "{{ rstudio_user }}"
        mode: "0644"
      become: false


    - name: Verify RStudio Server is running
      ansible.builtin.service:
        name: rstudio-server
        state: started
      register: rstudio_status
      retries: 3
      delay: 5
      until: rstudio_status is succeeded

    - name: Display RStudio Server access information
      ansible.builtin.debug:
        msg:
          - "RStudio Server is now running!"
      until: rstudio_status.state == 'started'
          - "Login with your Linux user credentials (user: {{ rstudio_user }})"

  handlers:
    - name: restart rstudio-server
      ansible.builtin.service:
        name: rstudio-server
        state: restarted
